<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1587714934056" stop="1587714940979">
	<name>Validating Title&apos;s of a page</name>
	<title>Validating Title&apos;s of a page</title>
	<test-cases>
		<test-case start="1587714934056" stop="1587714940278" status="passed">
			<name>Validating Banking App title in a Happy path</name>
			<title>Validating Banking App title in a Happy path</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
		<test-case start="1587714940279" stop="1587714940978" status="failed">
			<name>Validating Banking App title in a Non-Happy path</name>
			<title>Validating Banking App title in a Non-Happy path</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
			</attachments>
			<failure>
				<message>Expected &apos;Protractor practice website - Banking App&apos; to equal &apos;Protractor123 practice website - Banking App&apos;.</message>
				<stack-trace>Error: Failed expectation
    at C:\Users\Abhi\WebstormProjects\ProtractorTests\regression\ValidateTitlesTest.js:24:20
    at ManagedPromise.invokeCallback_ (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25
    at C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>