<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1588308931532' stop='1588308948745'>
    <name>Automating Customer Login functionality</name>
    <title>Automating Customer Login functionality</title>
    <test-cases>
        <test-case start='1588308931532' status='passed' stop='1588308945916'>
            <name>Login to the Account</name>
            <title>Login to the Account</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='9ab39559-50aa-41e6-a697-56c318ebb51d-attachment.png' type='image/png' size='22091'/>
            </attachments>
        </test-case>
        <test-case start='1588308945916' status='passed' stop='1588308947454'>
            <name>Validate Deposits</name>
            <title>Validate Deposits</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='43e43ede-6c00-41ab-8587-c9d7fe5e74f7-attachment.png' type='image/png' size='28667'/>
            </attachments>
        </test-case>
        <test-case start='1588308947454' status='failed' stop='1588308948744'>
            <name>Validate Withdrawl</name>
            <title>Validate Withdrawl</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='d08f80df-9598-40f2-b36d-d3a322c32efa-attachment.png' type='image/png' size='28286'/>
            </attachments>
            <failure>
                <message>Expected 'Transaction successful' to equal 'Transaction Successful'.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (C:\Users\Abhi\WebstormProjects\ProtractorTests\testSpecs\CustomerLogin.js:34:58)
                    at C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
                    at TaskQueue.execute_ (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2974:25
                    at C:\Users\Abhi\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>